export {default as Solution1} from '../images/Solution1.png'
export {default as Solution2} from '../images/Solution2.png'
export {default as Solution3} from '../images/Solution3.png'
export {default as Solution4} from '../images/Solution4.png'
export {default as Solution5} from '../images/Solution5.png'
export {default as Solution6} from '../images/Solution6.png'