export { default as ErrorIcon } from '../svg/404-image.svg'
export { default as Logo } from '../svg/Logo.svg'
export { default as Basketball } from '../svg/Basketball.svg'
export { default as BehanceIcon } from '../svg/BehanceIcon.svg'
export { default as FacebookIcon } from '../svg/FacebookIcon.svg'
export { default as InstagramIcon } from '../svg/InstagramIcon.svg'
export { default as TwitterIcon } from '../svg/TwitterIcon.svg'
export { default as DiscordIcon } from '../svg/DiscordIcon.svg'
export {default as HighSpeedIcon } from '../svg/HighSpeed.svg'
export {default as TechSupportIcon } from '../svg/TechSupport.svg'
export { default as LimitCostIcon } from '../svg/LimitCost.svg'
export {default as ITSystemIcon } from '../svg/ITSystem.svg'
export {default as InformationSecurityIcon } from '../svg/InformationSecurity.svg'
export {default as ServerAndStorageIcon } from '../svg/ServerAndStorage.svg'
export {default as SystemMaintenanceIcon } from '../svg/SystemMaintenance.svg'
export {default as DataCenterIcon } from '../svg/DataCenter.svg'
export {default as InfrastructureIcon } from '../svg/Infrastructure.svg'
export {default as CortexLogo} from '../svg/CortexLogo.svg'
export {default as PaloaltoLogo} from '../svg/PaloaltoLogo.svg'
export {default as PrismaLogo} from '../svg/PrismaLogo.svg'